# Generated by Django 3.2.7 on 2021-10-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_superhero_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='--'),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='--', max_length=200),
        ),
    ]
