# Generated by Django 3.2.7 on 2021-11-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weakness',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='--', max_length=200),
        ),
    ]
