# Generated by Django 3.2.7 on 2021-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_superhero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(max_length=200),
        ),
    ]
